

MACRO (ATS_TYPE_CHECK SRC)
	EXECUTE_PROCESS (
		COMMAND atscc -tc ${SRC}
		RESULT_VARIABLE _ATS_TC_RESULT
		OUTPUT_VARIABLE _ATS_TC_OUTPUT
		ERROR_VARIABLE _ATS_TC_ERROR
		OUTPUT_STRIP_TRAILING_WHITESPACE
		ERROR_STRIP_TRAILING_WHITESPACE)
	MESSAGE (STATUS ${_ATS_TC_OUTPUT})

	UNSET (_ATS_TC_RESULT)
	UNSET (_ATS_TC_OUTPUT)
	UNSET (_ATS_TC_ERROR)
ENDMACRO ()

MACRO (ATS_COMPILE OUTPUT SRC)

	IF (NOT "${OUTPUT}" MATCHES "^${OUTPUT}$")
		MESSAGE (STATUS "Parameter should be a variable instead of the value of variable!")
		MESSAGE (FATAL_ERROR "Example: ATS_COMPILE (C_OUTPUT, ${SOURCE_FILES})")
	ENDIF ()

	SET (_ATS_FILES ${SRC} ${ARGN})
	SET (_C_OUTPUT)
	SET (_PREFIX_SRC ${PROJECT_SOURCE_DIR})

	FOREACH (_ATS_FILE ${_ATS_FILES})
		#FOR STATIC FILES
		IF (${_ATS_FILE} MATCHES "\\.sats$")
			STRING(REPLACE ".sats" "_sats.c" _SATS_C ${_ATS_FILE})
			GET_FILENAME_COMPONENT (_SATS_C ${_SATS_C} NAME)
			ADD_CUSTOM_COMMAND (
			    OUTPUT ${_SATS_C} 
			    COMMAND atsopt ${ATS_INCLUDE} --output ${_SATS_C} --static ${_PREFIX_SRC}/${_ATS_FILE}
			    DEPENDS ${_PREFIX_SRC}/${_ATS_FILE}
		  	)
		  	LIST (APPEND _C_OUTPUT ${_SATS_C})
		#FOR DYNAMIC FILES
		ELSEIF (${_ATS_FILE} MATCHES "\\.dats$")
			STRING(REPLACE ".dats" "_dats.c" _DATS_C ${_ATS_FILE})
			GET_FILENAME_COMPONENT (_DATS_C ${_DATS_C} NAME)
			ADD_CUSTOM_COMMAND (
			    OUTPUT ${_DATS_C} 
			    COMMAND atsopt ${ATS_INCLUDE} --output ${_DATS_C} --dynamic ${_PREFIX_SRC}/${_ATS_FILE}
			    DEPENDS ${_PREFIX_SRC}/${_ATS_FILE}
		  	)
		  	LIST (APPEND _C_OUTPUT ${_DATS_C})
		ENDIF ()
	ENDFOREACH()

	SET (${OUTPUT} ${_C_OUTPUT})

	UNSET (_ATS_FILES)
	UNSET (_ATS_FILE)
	UNSET (_C_OUTPUT)
	UNSET (_SATS_C)
	UNSET (_DATS_C)
	UNSET (_PREFIX_SRC)

ENDMACRO ()

MACRO (ATS_INCLUDE_RESET)
	UNSET (ATS_INCLUDE)
	SET (ATS_INCLUDE)
ENDMACRO ()

MACRO (ATS_INCLUDE)
	SET (_INCLUDE)
	FOREACH (_PATH ${ARGN})
		SET (_INCLUDE ${_INCLUDE} -IATS ${_PATH})
	ENDFOREACH ()

	STRING (STRIP "${ATS_INCLUDE} ${_INCLUDE}" ATS_INCLUDE)
	UNSET (_INCLUDE)
ENDMACRO ()

MACRO (ATS_DEPGEN SRC)

	IF (${SRC} MATCHES "\\.dats$")
		EXECUTE_PROCESS (
			COMMAND atsopt --depgen=1 --dynamic ${SRC}
			RESULT_VARIABLE _ATS_DEPGEN_RESULT
			OUTPUT_VARIABLE _ATS_DEPGEN_OUTPUT
			ERROR_VARIABLE _ATS_DEPGEN_ERROR
			OUTPUT_STRIP_TRAILING_WHITESPACE
			ERROR_STRIP_TRAILING_WHITESPACE)
	ELSE ()
		EXECUTE_PROCESS (
			COMMAND atsopt --depgen=1 --static ${SRC}
			RESULT_VARIABLE _ATS_DEPGEN_RESULT
			OUTPUT_VARIABLE _ATS_DEPGEN_OUTPUT
			ERROR_VARIABLE _ATS_DEPGEN_ERROR
			OUTPUT_STRIP_TRAILING_WHITESPACE
			ERROR_STRIP_TRAILING_WHITESPACE)
	ENDIF ()

	MESSAGE (STATUS ${_ATS_DEPGEN_OUTPUT})

	UNSET (_ATS_DEPGEN_RESULT)
	UNSET (_ATS_DEPGEN_OUTPUT)
	UNSET (_ATS_DEPGEN_ERROR)
ENDMACRO ()