/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2012-10-31: 23h:44m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* prologues from statically loaded files */
/* external codes at top */

#include "test.cats"

/* type definitions */
/* external typedefs */
/* assuming abstract types */
/* sum constructor declarations */
/* exn constructor declarations */
/* static load function */

ats_void_type
_2home_2steinwaywhw_2GitHub_2ATS_CMake_2DepgenTest_2test1_2esats__staload () {
static int _2home_2steinwaywhw_2GitHub_2ATS_CMake_2DepgenTest_2test1_2esats__staload_flag = 0 ;
if (_2home_2steinwaywhw_2GitHub_2ATS_CMake_2DepgenTest_2test1_2esats__staload_flag) return ;
_2home_2steinwaywhw_2GitHub_2ATS_CMake_2DepgenTest_2test1_2esats__staload_flag = 1 ;

return ;
} /* staload function */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [/home/steinwaywhw/GitHub/ATS_CMake/DepgenTest/test1_sats.c] */
